roundUp <- function(x,to=10){
  to*(x%/%to + as.logical(x%%to))
}

Methods = list(
# HILIC Amino acids (3.25 min) --------------------------------------------
  "HILIC Amino acids (3.25 min)" = 
                 list(Gradient = data_frame(B2= c(85,85,5,5,85,85,85),
                                            A2= 100 - B2,
                                            Flow = 0.9,
                                            Time = c(0,0.7,2.55,2.75,2.8,3.25,3.95)),
                      SolventChannels = c("A2","B2"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                                 Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                                                 "50% Acetonitrile, 10 mM Ammonium Formate, 0.176% Formic Acid",
                                                                 "95:5:5 Acetonitrile:Methanol:Water, 10 mM Ammonium Formate, 0.176% Formic Acid",
                                                                 "Acetonitrile (B1)")),
                      Reagents = data.frame(Reagent = c("Ammonium Formate","Formic Acid (>99%)","Acetonitrile","Methanol","Water"),
                                            `MW (g/mol)` = c(63.0559,46.02538,NA,NA,NA),
                                            `Density (g/ml)` = c(1.28,1.22,NA,NA,NA),
                                            Concentration = c("prepare as 1 M\n in Water", "100%", "100%", "100%", "100%")),
                      Column = "Waters ACQUITY UPLC®BEH Amide column (2.1 x 100 mm, 1.7 μm)",
                      #Pressure = data.frame(Time = seq(0,3.95,0.05),
                       #                     Pressure = 600),
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`*2*0.88,
                                                  `Acetonitrile (ml)` = `Vol. total`/2,
                                                  `Methanol (ml)` = 0,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Formic Acid (ul)`/1000 - `NH4COOH (ml)`-`Methanol (ml)`),
                                  fd[fd$Solvent == "B2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)*1.05,
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`*2*0.88,
                                                  `Acetonitrile (ml)` = `Vol. total`/1.05*0.95,
                                                  `Methanol (ml)` = `Vol. total`/1.05*0.05,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Formic Acid (ul)`/1000 - `NH4COOH (ml)`-`Methanol (ml)`),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `NH4COOH (ml)` = NA,
                                                  `Formic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Methanol (ml)` = NA,
                                                  `Water (ml)` = NA))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","AAA_HILICamide_3min",fsep = "\\"),
                                    eq.method = "AAA_eq.m",
                                    eq.MRM = "AAA3min_MRM.m",
                                    analysis.method = c("20190528_AAA3min_dMRM_ISTD.m","AAA3min_MRM.m","AAA3min_dMRM.m","AAA3min_dMRM_ISTD.m"),
                                    final.wash.method.1 = "AAAWash1.m",
                                    final.wash.method.2 = "AAAWash2.m",
                                    nSTD = 7,
                                    brackets = 12)), 
# HILIC Amino acids (12 min) --------------------------------------------
"HILIC Amino acids (12 min)" = 
                 list(Gradient = data_frame(B2= c(85,85,5,5,85,85,85),
                                            A2= 100 - B2,
                                            Flow = 0.6,
                                            Time = c(0,3,10,11,11.05,12,12.7)),
                      SolventChannels = c("A2","B2"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                                 Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                                                 "50% Acetonitrile, 10 mM Ammonium Formate, 0.176% Formic Acid",
                                                                 "95:5:5 Acetonitrile:Methanol:Water, 10 mM Ammonium Formate, 0.176% Formic Acid",
                                                                 "Acetonitrile (B1)")),
                      Reagents = data.frame(Reagent = c("Ammonium Formate","Formic Acid (>99%)","Acetonitrile","Methanol","Water"),
                                            `MW (g/mol)` = c(63.0559,46.02538,NA,NA,NA),
                                            `Density (g/ml)` = c(1.28,1.22,NA,NA,NA),
                                            Concentration = c("prepare as 1 M\n in Water", "100%", "100%", "100%", "100%")),
                      Column = "Waters ACQUITY UPLC®BEH Amide column (2.1 x 100 mm, 1.7 μm)",
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`*2*0.88,
                                                  `Acetonitrile (ml)` = `Vol. total`/2,
                                                  `Methanol (ml)` = 0,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Formic Acid (ul)`/1000 - `NH4COOH (ml)`-`Methanol (ml)`),
                                  fd[fd$Solvent == "B2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)*1.05,
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`*2*0.88,
                                                  `Acetonitrile (ml)` = `Vol. total`/1.05*0.95,
                                                  `Methanol (ml)` = `Vol. total`/1.05*0.05,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Formic Acid (ul)`/1000 - `NH4COOH (ml)`-`Methanol (ml)`),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `NH4COOH (ml)` = NA,
                                                  `Formic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Methanol (ml)` = NA,
                                                  `Water (ml)` = NA))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","AAA_HILICamide_12min",fsep = "\\"),
                                    eq.method = "AAA_eq.m",
                                    #eq.MRM = "AAA12minMRM.m",
                                    analysis.method = c("20190530_AAA12min_dMRM_ISTD.m","AAA12min_MRM.m","AAA12min_dMRM.m","AAA12min_dMRM_ISTD.m"),
                                    final.wash.method.1 = "AAAWash1.m",
                                    final.wash.method.2 = "AAAWash2.m",
                                    nSTD = 7,
                                    brackets = 12)),
# RP Ion-pair Octylamine (8 min) --------------------------------------------
               "RP Ion-pair Octylamine (8 min)" = 
                 list(Gradient = data_frame(A1= c(95,95,30,20,30,95,95),
                                            B1= 100 - A1,
                                            Flow = 0.6,
                                            Time = c(0,3.5,6,6.5,6.7,7,8.7)),
                      SolventChannels = c("A1","B1"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                                 Composition = c("10% Acetonitrile, 4 mM Octylamine, 4 mM Acetic Acid",
                                                                 "50% Acetonitrile, 4 mM Octylamine, 4 mM Acetic Acid",
                                                                 "2:1 Water:Acetonitrile", "Acetonitrile",
                                                                 "33% Acetonitrile (A2)")),
                      Reagents = data.frame(Reagent = c("Octylamine","Acetic Acid (>99%)","Acetonitrile","Water"),
                                            `MW (g/mol)` = c(129.24,60.05,NA,NA),
                                            `Density (g/ml)` = c(0.782,1.049,NA,NA),
                                            Concentration = c("~6 M", "100%",  "100%", "100%")),
                      Column = "Agilent ZORBAX RRHD SB-C8, 2.1 x 100 mm, 1.8 µm",
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Octylamine (ul)` = 4*129.24/0.782*`Vol. total`/10^3 ,
                                                  `Acetic Acid (ul)` = 4*60.05/1.049*`Vol. total`/10^3,
                                                  `Acetonitrile (ml)` = `Vol. total`*0.1,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Acetic Acid (ul)`/10^3 - `Octylamine (ul)`/10^3),
                                  fd[fd$Solvent == "B1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Octylamine (ul)` = 4*129.24/0.782*`Vol. total`/10^3 ,
                                                  `Acetic Acid (ul)` = 4*60.05/1.049*`Vol. total`/10^3,
                                                  `Acetonitrile (ml)` = `Vol. total`*0.5,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Acetic Acid (ul)`/10^3 - `Octylamine (ul)`/10^3),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `Octylamine (ul)` = NA,
                                                  `Acetic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`/3,
                                                  `Water (ml)` = `Vol. total`*2/3))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","RP_IP_Octylamine_8min",fsep = "\\"),
                                    eq.MRM = "OctNH2MRM.m",
                                    analysis.method = "OctNH2dMRM.m",
                                    nSTD = 7,
                                    brackets = 12)),
# RP Ion-pair Tributylamine dMRM Agilent Kit (18 min) --------------------------------------------
               "RP Ion-pair Tributylamine dMRM Agilent Kit (18 min)" = 
                 list(Gradient = data_frame(A1= c(rep(100,3),80,55,1,1,100,1,1,rep(100,4)),
                                            B1= c(rep(0,3),20,45,99,99,rep(0,7)),
                                            B2 = 100-A1-B1,
                                            Flow = c(rep(0.325,8),rep(1,2),rep(0.6,2),rep(0.325,2)),
                                            Time = c(0,1.5,1.51,5,10,10.05,12,12,12.01,15,15.01,16,16.01,18.7)),
                      SolventChannels = c("A1","B1","B2"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","B2","Needle Wash"),
                                                 Composition = c("3% Methanol, 15 mM Acetic Acid, 10 mM Tributylamine",
                                                                 "97% ACN, 3% Methanol 15 mM Acetic Acid, 10 mM Tributylamine",
                                                                 "Acetonitrile",
                                                                 "50% Methanol, 15 mM Acetic Acid")),
                      Reagents = data.frame(Reagent = c("Tributylamine","Acetic Acid (>99%)","Acetonitrile","Methanol","Water"),
                                            `MW (g/mol)` = c(185.36,60.05,NA,NA,NA),
                                            `Density (g/ml)` = c(0.78,1.049,NA,NA,NA),
                                            Concentration = c("~4.2 M", "100%", "100%", "100%", "100%")),
                      Column = "Agilent ZORBAX RRHD Extend 80Å C18, 2.1 x 100 mm, 1.8 µm, 1200 bar",
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Tributylamine (ul)` = 10*185.36/0.78*`Vol. total`/10^3 ,
                                                  `Acetic Acid (ul)` = 15*60.05/1.049*`Vol. total`/10^3,
                                                  `Methanol (ml)` = `Vol. total`*0.03,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Water (ml)` = `Vol. total` - `Methanol (ml)` - `Acetic Acid (ul)`/10^3 - `Tributylamine (ul)`/10^3),
                                  fd[fd$Solvent == "B1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Tributylamine (ul)` = 10*185.36/0.78*`Vol. total`/10^3 ,
                                                  `Acetic Acid (ul)` = 15*60.05/1.049*`Vol. total`/10^3,
                                                  `Methanol (ml)` = `Vol. total`*0.03,
                                                  `Acetonitrile (ml)` = `Vol. total` - `Methanol (ml)` - `Acetic Acid (ul)`/10^3 - `Tributylamine (ul)`/10^3,
                                                  `Water (ml)` =  NA),
                                  fd[fd$Solvent == "B2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Tributylamine (ul)` = NA,
                                                  `Acetic Acid (ul)` = NA,
                                                  `Methanol (ml)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Water (ml)` =  NA),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `Tributylamine (ul)` = NA,
                                                  `Acetic Acid (ul)` = 15*60.05/1.049*`Vol. total`/10^3,
                                                  `Methanol (ml)` = `Vol. total`*0.5,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Water (ml)` =  `Vol. total`*0.5 -`Acetic Acid (ul)`/10^3))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    splitWash = T,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","RP_IP_TBA_dMRMKit_short",fsep = "\\"),
                                    eq.MRM = "dMRMKit_shortMRM.m",
                                    analysis.method = "dMRMKit_shortdMRM.m",
                                    wash.method = "dMRMKit_shortWash.m",
                                    nSTD = 7,
                                    brackets = 12)),
# RP Ion-pair Tributylamine Buescher (40 min) --------------------------------------------
               "RP Ion-pair Tributylamine Buescher (40 min)" = 
                 list(Gradient = data_frame(B1= c(rep(0,2),2,9,9,25,50,50,rep(0,3)),
                                            A1 = 100-B1,
                                            Flow = c(rep(0.4,3),0.35,rep(0.25,2),rep(0.15,3),rep(0.4,2)),
                                            Time = c(0,5,10,11,16,18,19,25,26,32,40)),
                      SolventChannels = c("A1","B1"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","Needle Wash"),
                                                 Composition = c("5% (v/v) Methanol, 15 mM Acetic Acid, 10 mM Tributylamine",
                                                                 "2-Propanol",
                                                                 "50% Methanol, 15 mM Acetic Acid")),
                      Reagents = data.frame(Reagent = c("Tributylamine","Acetic Acid (>99%)","2-Propanol","Methanol","Water"),
                                            `MW (g/mol)` = c(185.36,60.05,NA,NA,NA),
                                            `Density (g/ml)` = c(0.78,1.049,NA,NA,NA),
                                            Concentration = c("~4.2 M", "100%", "100%", "100%", "100%")),
                      Column = "Waters ACQUITY UPLC HSS T3 Column, 100Å, 1.8 µm, 2.1 mm X 150 mm", 
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Tributylamine (ul)` = 10*185.36/0.78*`Vol. total`/10^3 ,
                                                  `Acetic Acid (ul)` = 15*60.05/1.049*`Vol. total`/10^3,
                                                  `Methanol (ml)` = `Vol. total`*0.05,
                                                  `2-Propanol (ml)` = NA,
                                                  `Water (ml)` = `Vol. total` - `Methanol (ml)` - `Acetic Acid (ul)`/10^3 - `Tributylamine (ul)`/10^3),
                                  fd[fd$Solvent == "B1",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Tributylamine (ul)` = NA,
                                                  `Acetic Acid (ul)` = NA,
                                                  `Methanol (ml)` = NA,
                                                  `2-Propanol (ml)` = `Vol. total`,
                                                  `Water (ml)` =  NA),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `Tributylamine (ul)` = NA,
                                                  `Acetic Acid (ul)` = 15*60.05/1.049*`Vol. total`/10^3,
                                                  `Methanol (ml)` = `Vol. total`*0.5,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Water (ml)` =  `Vol. total`*0.5 -`Acetic Acid (ul)`/10^3))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","RP_IP_TBA_Buescher",fsep = "\\"),
                                    #eq.MRM = "TBABuescher.MRM",
                                    analysis.method = "TBABuescher.MRM",
                                    #wash.method = "dMRMKit_shortWash.m",
                                    nSTD = 7,
                                    brackets = 12)),
# HILIC AXP HTP --------------------------------------------
               "HILIC AXP HTP" = list(
                 Gradient = data_frame(B2= c(70,70,40,40,70,70),
                                       A2= 100 - B2,
                                       Flow = 0.4,
                                       Time = c(0,1.5,3,3.2,3.25,4)),
                 SolventChannels = c("A2","B2"),
                 SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                            Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                                            "10 mM Ammonium Bicarbonate, 0.25% Ammonium Hydroxide",
                                                            "Acetonitrile",
                                                            "Acetonitrile (B2)")),
                 Reagents = data.frame(Reagent = c("Ammonium Bicarbonate","Ammonium hydroxide","Acetonitrile","Water"),
                                       `MW (g/mol)` = c(79.06,35.04,NA,NA),
                                       `Density (g/ml)` = c(NA,0.91,NA,NA),
                                       Concentration = c("prepare as 1 M in Water", "25% (w/w)", "100%", "100%")),
                 Column = "Waters ACQUITY UPLC BEH Amide column (2.1 x 100 mm, 1.7 ?m)",
                 #Pressure = data.frame(Time = seq(0,3.95,0.05),
                 #                     Pressure = 600),
                 calcSolvents = function(fd){
                   bind_rows(fd[fd$Solvent == "A2",] %>%
                               dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                             `1 M NH4HCO3 (ml)` = `Vol. total`/100,
                                             `25% w/w NH4OH (ml)` = `Vol. total`/100,
                                             `Acetonitrile (ml)` = `Vol. total`/2,
                                             `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `1 M NH4HCO3 (ml)` - `25% w/w NH4OH (ml)`),
                             fd[fd$Solvent == "B2",] %>%
                               dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                             `1 M NH4HCO3 (ml)` = NA,
                                             `25% w/w NH4OH (ml)` = NA,
                                             `Acetonitrile (ml)` = `Vol. total`,
                                             `Water (ml)` = NA),
                             fd[fd$Solvent == "Needle Wash",] %>%
                               dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                             `1 M NH4HCO3 (ml)` = NA,
                                             `25% w/w NH4OH (ml)` = NA,
                                             `Acetonitrile (ml)` = `Vol. total`,
                                             `Water (ml)` = NA))
                 },
                 WL.fun = list(filename = NULL,
                               sample.path = NULL,
                               method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","HILIC_AXP",fsep = "\\"),
                               analysis.method = c("HILIC_AXP_4min.m"),
                               nSTD = 7,
                               brackets = 12)),
# RP Dansyl-Polyamines --------------------------------------------
               "RP Dansyl-Polyamines" = 
                 list(Gradient = data_frame(B2= c(60,60,100,100,60,60),
                                            A2= 100 - B2,
                                            Flow = 0.5,
                                            Time = c(0,0.4,3.5,3.8,3.81,5.7)),
                      SolventChannels = c("A2","B2"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                                 Composition = c("2:1 Water:Acetonitrile", 
                                                                 "Acetonitrile",
                                                                 "0.1% Formic Acid",
                                                                 "Acetonitrile",
                                                                 "Acetonitrile (B1)")),
                      Reagents = data.frame(Reagent = c("Formic Acid (>99%)","Acetonitrile","Water"),
                                            `MW (g/mol)` = c(46.02538,NA,NA),
                                            `Density (g/ml)` = c(1.22,NA,NA),
                                            Concentration = c(">99%", "100%", "100%")),
                      Column = "ZORBAX Eclipse Plus C18, RRHD, 2.1 x 50 mm 1.8 m",
                      #Pressure = data.frame(Time = seq(0,3.95,0.05),
                      #                     Pressure = 600),
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Formic Acid (ul)` = `Vol. total`,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Water (ml)` = `Vol. total` - `Formic Acid (ul)`/1000),
                                  fd[fd$Solvent == "B2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `Formic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `Formic Acid (ul)`/1000),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `Formic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Water (ml)` = NA))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","RP Dansyl-Polyamines",fsep = "\\"),
                                    analysis.method = c("RP_DansylPolyamines.m"),
                                    nSTD = 7,
                                    brackets = 12)),
# RP Nucleosides --------------------------------------------
               "RP Nucleosides" = 
                 list(Gradient = data_frame(B2= c(rep(2,2),25,rep(80,2),rep(2,4)),
                                            A2= 100 - B2,
                                            Flow = c(rep(0.2,6),0.6, rep(0.2,2)),
                                            Time = c(0,2,10,11.5,15,16,22,22.5,23.7)),
                      SolventChannels = c("A2","B2"),
                      SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                                                 Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                                                 "100% Water+ 0.1% formic acid+10 mM ammonium formate",
                                                                 "100% Methanol + 0.1% formic acid+ 10 mM ammonium formate",
                                                                 "2:1 Water:Acetonitrile")),
                      Reagents = data.frame(Reagent = c("Ammonium Formate","Formic Acid (>99%)","Methanol","Water"),
                                            `MW (g/mol)` = c(63.0559,46.02538,NA,NA),
                                            `Density (g/ml)` = c(1.28,1.22,NA,NA),
                                            Concentration = c("prepare as 1 M\n in Water", "100%", "100%", "100%")),
                      Column = "Zorbax Eclipse Plus C18 2.1x100mm 1.8 Micron",
                      #Pressure = data.frame(Time = seq(0,3.95,0.05),
                      #                     Pressure = 600),
                      calcSolvents = function(fd){
                        bind_rows(fd[fd$Solvent == "A2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Methanol (ml)` = 0,
                                                  `Water (ml)` = `Vol. total` - `Formic Acid (ul)`/1000 - `NH4COOH (ml)`),
                                  fd[fd$Solvent == "B2",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100),
                                                  `NH4COOH (ml)` = `Vol. total`/100,
                                                  `Formic Acid (ul)` = `Vol. total`,
                                                  `Acetonitrile (ml)` = NA,
                                                  `Methanol (ml)` = `Vol. total`-`Formic Acid (ul)`/1000 - `NH4COOH (ml)`,
                                                  `Water (ml)` = NA),
                                  fd[fd$Solvent == "Needle Wash",] %>%
                                    dplyr::mutate(`Vol. total` = roundUp(exact,100)+50,
                                                  `NH4COOH (ml)` = NA,
                                                  `Formic Acid (ul)` = NA,
                                                  `Acetonitrile (ml)` = `Vol. total`,
                                                  `Methanol (ml)` = NA,
                                                  `Water (ml)` = NA))
                      },
                      WL.fun = list(filename = NULL,
                                    sample.path = NULL,
                                    method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","RP Nucleosides",fsep = "\\"),
                                    analysis.method = c("RP Nucleosides_C18-100mm.m"),
                                    nSTD = 7,
                                    brackets = 12)),
# HILIC basic 10 min in Development --------------------------------------------
"HILIC basic 10 min in Development" = list(
  Gradient = data_frame(B2= c(70,70,40,40,70,70),
                        A2= 100 - B2,
                        Flow = 0.3,
                        Time = c(0,3,7.5,8,8.1,10)),
  SolventChannels = c("A2","B2"),
  SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                             Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                             "10 mM Ammonium Bicarbonate, 0.25% Ammonium Hydroxide",
                                             "Acetonitrile",
                                             "Acetonitrile (B2)")),
  Reagents = data.frame(Reagent = c("Ammonium Bicarbonate","Ammonium hydroxide","Acetonitrile","Water"),
                        `MW (g/mol)` = c(79.06,35.04,NA,NA),
                        `Density (g/ml)` = c(NA,0.91,NA,NA),
                        Concentration = c("prepare as 1 M in Water", "25% (w/w)", "100%", "100%")),
  Column = "Waters ACQUITY UPLC BEH Amide column (2.1 x 100 mm, 1.7 ?m)",
  #Pressure = data.frame(Time = seq(0,3.95,0.05),
  #                     Pressure = 600),
  calcSolvents = function(fd){
    bind_rows(fd[fd$Solvent == "A2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = `Vol. total`/100,
                              `25% w/w NH4OH (ml)` = `Vol. total`/100,
                              `Acetonitrile (ml)` = 0,
                              `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `1 M NH4HCO3 (ml)` - `25% w/w NH4OH (ml)`),
              fd[fd$Solvent == "B2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = NA,
                              `25% w/w NH4OH (ml)` = NA,
                              `Acetonitrile (ml)` = `Vol. total`,
                              `Water (ml)` = NA),
              fd[fd$Solvent == "Needle Wash",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = NA,
                              `25% w/w NH4OH (ml)` = NA,
                              `Acetonitrile (ml)` = `Vol. total`,
                              `Water (ml)` = NA))
  },
  WL.fun = list(filename = NULL,
                sample.path = NULL,
                method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","HILIC_basic_10min_inDev",fsep = "\\"),
                analysis.method = c("20180312_HILIC_basic_10min_inDev.m"),
                nSTD = 7,
                brackets = 12)),
# HILIC basic 8 min high flow - in Development --------------------------------------------
"HILIC basic 8 min high flow" = list(
  Gradient = data_frame(B2= c(95,95,50,50,95,95),
                        A2= 100 - B2,
                        Flow = 0.6,
                        Time = c(0,2.5,5.5,7,7.1,8.5)),
  SolventChannels = c("A2","B2"),
  SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                             Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                             "10% ACN, 3 mM Ammonium Bicarbonate, 0.075% Ammonium Hydroxide",
                                             "80% ACN, 3 mM Ammonium Bicarbonate, 0.075% Ammonium Hydroxide",
                                             "Acetonitrile (B2)")),
  Reagents = data.frame(Reagent = c("Ammonium Bicarbonate","Ammonium hydroxide","Acetonitrile","Water"),
                        `MW (g/mol)` = c(79.06,35.04,NA,NA),
                        `Density (g/ml)` = c(NA,0.91,NA,NA),
                        Concentration = c("prepare as 1 M in Water", "25% (w/w)", "100%", "100%")),
  Column = "Waters ACQUITY UPLC BEH Amide column (2.1 x 100 mm, 1.7 ?m)",
  #Pressure = data.frame(Time = seq(0,3.95,0.05),
  #                     Pressure = 600),
  calcSolvents = function(fd){
    bind_rows(fd[fd$Solvent == "A2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = `Vol. total`*0.003,
                              `25% w/w NH4OH (ml)` = `Vol. total`*0.003,
                              `Acetonitrile (ml)` = `Vol. total`*0.1,
                              `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `1 M NH4HCO3 (ml)` - `25% w/w NH4OH (ml)`),
              fd[fd$Solvent == "B2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = `Vol. total`*0.003,
                              `25% w/w NH4OH (ml)` = `Vol. total`*0.003,
                              `Acetonitrile (ml)` = `Vol. total`*0.8,
                              `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `1 M NH4HCO3 (ml)` - `25% w/w NH4OH (ml)`),
              fd[fd$Solvent == "Needle Wash",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `1 M NH4HCO3 (ml)` = NA,
                              `25% w/w NH4OH (ml)` = NA,
                              `Acetonitrile (ml)` = `Vol. total`,
                              `Water (ml)` = NA))
  },
  WL.fun = list(filename = NULL,
                sample.path = NULL,
                method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","HILIC_basic_10min_inDev",fsep = "\\"),
                analysis.method = c("20180322_HILIC_basic_10min_inDev_highFlow.m"),
                nSTD = 7,
                brackets = 12)),
# HILIC basic method - in Development --------------------------------------------
"HILIC basic 100 mM (NH4)2CO3, on 150 mm" = list(
  Gradient = data_frame(B2= c(70,70,40,40,70,70),
                        A2= 100 - B2,
                        Flow = 0.45,
                        Time = c(0,3,7,8,8.1,10.5)),
  SolventChannels = c("A2","B2"),
  SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                             Composition = c("Water", "Acetonitrile",
                                             "100 mM Ammonium carbonate",
                                             "100% Acetonitrile",
                                             "50% MeOH")),
  Reagents = data.frame(Reagent = c("Ammonium carbonate","Acetonitrile","Water"),
                        `MW (g/mol)` = c(96.09,NA,NA),
                        `Density (g/ml)` = c(NA,NA,NA),
                        Concentration = c("weigh into bottle", "100%", "100%")),
  Column = "Waters ACQUITY UPLC BEH Amide column (2.1 x 150 mm, 1.7 um)",
  #Pressure = data.frame(Time = seq(0,3.95,0.05),
  #                     Pressure = 600),
  calcSolvents = function(fd){
    bind_rows(fd[fd$Solvent == "A2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `(NH4)2CO3 (g)` = `Vol. total`*96.09*0.1/1000,
                              `Acetonitrile (ml)` = NA,
                              `Water (ml)` = `Vol. total`),
              fd[fd$Solvent == "B2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `(NH4)2CO3 (g)` = NA,
                              `Acetonitrile (ml)` = roundUp(exact,100),
                              `Water (ml)` = NA),
              fd[fd$Solvent == "Needle Wash",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `Acetonitrile (ml)` = NA,
                              `MeOH` = `Vol. total`/2,
                              `Water (ml)` = `Vol. total`/2))
  },
  WL.fun = list(filename = NULL,
                sample.path = NULL,
                method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","CentralCMetabolism_HILIC",fsep = "\\"),
                analysis.method = c("20181127_dMRM_150mm_13CandNatural.m"),
                eq.method = "HILIC_eq.m",
                eq.MRM = "20181127_MRM_150mm_Natural.m",
                nSTD = 7,
                brackets = 12)),
# HILIC basic method - in Development --------------------------------------------
"HILIC basic 100 mM (NH4)2CO3, on 100 mm" = list(
  Gradient = data_frame(B2= c(70,70,40,40,70,70),
                        A2= 100 - B2,
                        Flow = 0.3,
                        Time = c(0,3,7,8,8.1,10.5)),
  SolventChannels = c("A2","B2"),
  SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                             Composition = c("Water", "Acetonitrile",
                                             "100 mM Ammonium carbonate",
                                             "100% Acetonitrile",
                                             "50% MeOH")),
  Reagents = data.frame(Reagent = c("Ammonium carbonate","Acetonitrile","Water"),
                        `MW (g/mol)` = c(96.09,NA,NA),
                        `Density (g/ml)` = c(NA,NA,NA),
                        Concentration = c("weigh into bottle", "100%", "100%")),
  Column = "Waters ACQUITY UPLC BEH Amide column (2.1 x 150 mm, 1.7 um)",
  #Pressure = data.frame(Time = seq(0,3.95,0.05),
  #                     Pressure = 600),
  calcSolvents = function(fd){
    bind_rows(fd[fd$Solvent == "A2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `(NH4)2CO3 (g)` = `Vol. total`*96.09*0.1/1000,
                              `Acetonitrile (ml)` = NA,
                              `Water (ml)` = `Vol. total`),
              fd[fd$Solvent == "B2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `(NH4)2CO3 (g)` = NA,
                              `Acetonitrile (ml)` = roundUp(exact,100),
                              `Water (ml)` = NA),
              fd[fd$Solvent == "Needle Wash",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `Acetonitrile (ml)` = NA,
                              `MeOH` = `Vol. total`/2,
                              `Water (ml)` = `Vol. total`/2))
  },
  WL.fun = list(filename = NULL,
                sample.path = NULL,
                method.path = file.path("D:","MassHunter","Methods","B.07.00","000_SOPs","CentralCMetabolism_HILIC",fsep = "\\"),
                analysis.method = c("20190628_dMRM_100mm_Natural.m","20190628_dMRM_100mm_13CandNatural.m","20181126_MRM_100mm_Natural.m","20190827_SRM_sugarP.m"),
                eq.method = "HILIC_eq.m",
                eq.MRM = "20181126_MRM_100mm_Natural.m",
                nSTD = 7,
                brackets = 12)),
# HILIC-Z Agilent Method --------------------------------------------
"HILIC-Z Agilent Method" = list(
  Gradient = data_frame(B2= c(90,90,60,60,90,90),
                        A2= 100 - B2,
                        Flow = 0.25,
                        Time = c(0,2,12,15,15.1,23)),
  SolventChannels = c("A2","B2"),
  SolventSystem = data.frame(Solvent = c("A1","B1","A2","B2","Needle Wash"),
                             Composition = c("2:1 Water:Acetonitrile", "Acetonitrile",
                                             "10 mM NH4Ac. pH9, 5 uM Medronic Acid",
                                             "90% Acetonitrile, 10 mM NH4Ac. pH9, 5 uM Medronic Acid",
                                             "Acetonitrile (B2)")),
  Reagents = data.frame(Reagent = c("100 mM Ammonium Acetate pH9","100 mM Medronic Acid","Acetonitrile","Water"),
                        `MW (g/mol)` = c(NA,NA,NA,NA),
                        `Density (g/ml)` = c(NA,NA,NA,NA),
                        Concentration = c(NA,NA,NA,NA)),#c("prepare as 1 M in Water", "25% (w/w)", "100%", "100%")),
  Column = "Agilent Poroshell 120 HILIC-Z column (2.1 x 150 mm, 2.7 um)",
  #Pressure = data.frame(Time = seq(0,3.95,0.05),
  #                     Pressure = 600),
  calcSolvents = function(fd){
    bind_rows(fd[fd$Solvent == "A2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `100 mM Ammonium Acetate pH9 (ml)` = `Vol. total`/10,
                              `100 mM Medronic Acid (ul)` = `Vol. total`/20,
                              `Acetonitrile (ml)` = 0,
                              `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `100 mM Ammonium Acetate pH9 (ml)`),
              fd[fd$Solvent == "B2",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `100 mM Ammonium Acetate pH9 (ml)` = `Vol. total`/10,
                              `100 mM Medronic Acid (ul)` = `Vol. total`/20,
                              `Acetonitrile (ml)` = `Vol. total`*0.9,
                              `Water (ml)` = `Vol. total` - `Acetonitrile (ml)` - `100 mM Ammonium Acetate pH9 (ml)`),
              fd[fd$Solvent == "Needle Wash",] %>%
                dplyr::mutate(`Vol. total` = roundUp(exact,100),
                              `100 mM Ammonium Acetate pH9 (ml)` = NA,
                              `100 mM Medronic Acid (ul)` = NA,
                              `Acetonitrile (ml)` = `Vol. total`,
                              `Water (ml)` = NA))
  },
  WL.fun = list(filename = NULL,
                sample.path = NULL,
                method.path = file.path("D:","MassHunter","Methods","B.07.00","Sreejith","AgiletnPoroShell",fsep = "\\"),
                analysis.method = c("20190718_OriginalMethod_dMRM.m","20190718_OriginalMethod_SRMP.m"),
                eq.MRM = "20190718_OriginalMethod_MRM.m",
                nSTD = 7,
                brackets = 12)))
